[project]
name = "MJ02"
version = "0.0.1"
dependencies = [
    "certifi>=2026.7.22",
    "dvc>=3.67.1",
    "geopandas>=1.1.4",
    "netcdf4>=1.7.4",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pyogrio>=0.13.0",
    "xarray>=2026.7.0",
    "xlrd>=2.0.2",
]

authors = [
  { name = "Mike Li"}
]
